'use client';

import React from 'react';
import { Evidence, Task } from '../../core/types';

interface ExecutionEvidencePanelProps {
  evidence?: Evidence | null;
  task?: Task | null;
  isFailureDemo?: boolean;
}

export const ExecutionEvidencePanel: React.FC<ExecutionEvidencePanelProps> = ({
  evidence,
  task,
  isFailureDemo
}) => {
  const isSubmitted = task?.status === 'SUBMITTED' || Boolean(evidence);
  const isFailed = task?.status === 'FAILED' || isFailureDemo;

  const payload = evidence?.evidencePayload || {};
  const outputCode = (payload.outputCode as string) || (isFailureDemo
    ? `def process_payment(amount, risk_score):\n    # BUG: Incorrect risk deduction formula\n    return amount - (risk_score * 1000)`
    : `def process_payment(amount, risk_score):\n    # Deterministic risk deduction formula\n    deduction = Math.round(amount * (risk_score / 100.0))\n    return max(0, amount - deduction)`);

  const provider = (payload.provider as string) || 'Google';
  const adapter = (payload.adapter as string) || 'GEMINI_DEBUGGER';
  const model = (payload.model as string) || 'gemini-2.5-flash';
  const executionTimeMs = (payload.executionTimeMs as number) || 45;

  const outputHash = evidence?.outputHash || 'bb94368a43c2c4ac981...';
  const evidenceHash = evidence?.evidenceHash || 'e3b0c44298fc1c149af...';

  return (
    <div className="w-full bg-white border border-[#dadce0] rounded shadow-sm overflow-hidden mb-6">
      <div className="px-5 py-4 border-b border-[#dadce0] bg-[#f8f9fa] flex items-center justify-between">
        <div>
          <h3 className="font-semibold text-[#202124] text-[15px] uppercase tracking-wider">EXECUTION & EVIDENCE ADAPTER</h3>
          <p className="text-[12px] text-[#5f6368] mt-0.5">Execution Adapter: {adapter} ({provider})</p>
        </div>
        <span className={`text-[12px] px-3 py-1 rounded font-medium border bg-white ${
          isFailed ? 'text-[#c5221f] border-[#fce8e6]' : isSubmitted ? 'text-[#137333] border-[#ceead6]' : 'text-[#3c4043] border-[#dadce0]'
        }`}>
          {isFailed ? 'EXECUTION FAILED' : isSubmitted ? 'ARTIFACT SUBMITTED' : 'AWAITING EXECUTION'}
        </span>
      </div>

      <div className="p-5 flex flex-col xl:flex-row gap-6">
        {/* Output Artifact Code */}
        <div className="flex-1 overflow-x-auto">
          <div className="flex justify-between items-center mb-2 border-b border-[#dadce0] pb-2">
            <span className="text-[11px] font-bold text-[#5f6368] uppercase tracking-wider">
              Model Returned Output Artifact
            </span>
            <span className="text-[11px] font-mono text-[#5f6368]">
              {provider} • {model} ({executionTimeMs}ms)
            </span>
          </div>
          <pre className="p-4 bg-[#f8f9fa] border border-[#dadce0] rounded text-[12px] font-mono text-[#202124] overflow-x-auto max-h-60">
            {outputCode}
          </pre>
          <p className="text-[11px] text-[#5f6368] mt-2 italic">
            * Note: Model returned an execution artifact. Proof/evidence integrity hash generated by system.
          </p>
        </div>

        {/* Evidence Hash Package */}
        <div className="w-full xl:w-80 flex-shrink-0 xl:border-l xl:border-[#dadce0] xl:pl-6">
          <span className="block text-[11px] font-bold text-[#5f6368] uppercase tracking-wider mb-4 border-b border-[#dadce0] pb-2">
            Cryptographic Evidence Package
          </span>
          
          <div className="space-y-4 text-[12px]">
            <div>
              <span className="block text-[11px] text-[#5f6368] uppercase">Execution Adapter</span>
              <span className="block text-[14px] font-semibold text-[#1a73e8] font-mono">{adapter}</span>
            </div>
            <div>
              <span className="block text-[11px] text-[#5f6368] uppercase">Output Hash (SHA-256)</span>
              <span className="block font-mono text-[#1a73e8] text-[11px] break-all bg-[#f8f9fa] p-1.5 border border-[#dadce0] rounded mt-0.5">
                {outputHash}
              </span>
            </div>
            <div>
              <span className="block text-[11px] text-[#5f6368] uppercase">Evidence Hash (SHA-256)</span>
              <span className="block font-mono text-[#1a73e8] text-[11px] break-all bg-[#f8f9fa] p-1.5 border border-[#dadce0] rounded mt-0.5">
                {evidenceHash}
              </span>
            </div>
            <div>
              <span className="block text-[11px] text-[#5f6368] uppercase">Verification Status</span>
              <span className="block font-semibold text-[#202124]">
                {isSubmitted ? 'SUBMITTED (Ready for Verification)' : 'PENDING'}
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
